### ISSUE TITLE
Zgłaszanie obecności

### ISSUE THREAD

**Issue by Gumkle** [akai-org/akai_manager_python#3]
Zgłaszanie obecności może się odbywać dwojako :
1. Przejście do strony rejestracji na wydarzenie (docelowo widok meetings/templates/meetings/meeting_register.html), na której będzie input do wpisania kodu. Kiedy użytkownik wpisze taki kod to zostaje przekierowany na url który go odbiera i rozpoczyna szukanie spotkania o takim samym kodzie wśród obecnie aktywnych spotkań. Jeżeli takie znajdzie to dopisuje użytkownika do listy obecnych na tym spotkaniu i przekierowuje go na stronę zawierającą szczegóły tego spotkania (opisanego w #1 ).
2. Użytkownik może zeskanować kod QR, który przeniesie go bezpośrednio do url odbierającego kod z już wpisanym kodem i z pominięciem formularza wpisywania kodu.

**Comment by cozajeden** [comment]
1. Zrobione.

**Comment by cozajeden** [comment]
Model Attendance przechowuje listę obecności

**Comment by cozajeden** [comment]
Poprawiono:
-Model Attendance usunięty. Teraz obecność zapisuje się w relacji many to many w modelu Meeting.
-Kod do listy obecności jest liczbą 6-cio cyfrową
-Kod generuje się przy aktywacji spotkania i deaktywacja go usuwa
-Kod już się nie zmienia przy aktualizacji danych spotkania
-Dodano feedback dla użytkownika w przypadku wprowadzenia nieistniejącego kodu
