### ISSUE TITLE
Dziwne wyświetlanie ryszard.poznanski

### ISSUE THREAD

**Issue by Gumkle** [akai-org/akai_manager_python#57]
Imię i nazwisko wyświetla się jako ====== a po wejściu w szczegóły w ogóle nie wyświetla się avatar: http://manager.akai.org.pl/members/3/. Tak powinno być?

**Comment by Cheriit** [comment]
Wiąże się to z tym, że avatar oraz imię i nazwisko brane są z konta akai.org.pl
Bez podanego imienia i nazwiska nie ma na podstawie czego też wygenerować awatara

**Comment by Gumkle** [comment]
Ciekawe, bo każdemu podawałem imię i nazwisko. Może usunął? Sprawdzę to. Może w takim razie warto dać jakiś awatar-zaślepkę i informację o braku imienia i nazwiska?

**Comment by Gumkle** [comment]
@Cheriit  Sprawdziłem go i ma w Google podane imię i nazwisko. Avatara nie ma ale tak samo jak na przykład Ula albo Ty a jednak Wam wyświetla się literka.

**Comment by Cheriit** [comment]
To jest na serio dziwne w takim razie. Dodałem defaultową wartość loga czyli nasze logo AKAI'owe ale i tak to dość dziwne
